
apiVersion: v1
clusters:
- cluster:
    server: https://C71126CD706E8CBC138F8B9688E18206.yl4.eu-central-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJU1FNeWdMRXEvcDR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeU1EUXlNVFUzTVRsYUZ3MHpOREV5TURJeU1qQXlNVGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNqZzJPSkx0TmZjc2Jwd2xRR3NKM0NPdXNBcUZBZGFaamdTVTVnOUc2SDI4TXQrRGxrTUFSK1grMzcKZW1UUzY3Z0gxNm9qNzluc1pOMUpvdW53RkU2MEpxNnArYnZEUUpMdGd3NnBGUis1TS9jMDhEMm5WWWV1dTdZUAo3Tkw4MHlRaVNtcVhUcUF4dGZtR3NPTStqOUZ1THM5ejllREV4RU05Yk1yNytrN3BBUkZTQmVYdDc5bjYxdjc5CmJpUzN4eDVpYlJtNzhTZWlCc1ZEODl5aXZubFVPUFJSamxUWWt2akxnTk5QeW5jUW1pSTJQc1F6MVpvTmRITCsKSElHbHdGeDQ0NVJyR1I2Qk1oUVRGaXFzV3ZSL09yMDZ2bFVGcEthc1FMNFY4dVBBZTBsS3VxUDI0N2l2ZjBzSQpyeThYL3NBcVRqaDZ4cU53WmVuL3ptOGpDZStCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUZnQ0KzdUNmpCUFZaWnova3FzdkN0M2xTbEFEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTFQR1k4ODdiUQpvTHE0dmdHUGduMGsrWjIrSUhQNGw3OWxNK29LeEpaT0hpUWU5V1hrUjZNbXM2bEQ1SzF0eXhyZW1Od1QzWk4vCmV6WWk1NHk4Y2FxVUJWRTZuWDJHaE8zY3IwVGp6T2VHVlNSc1lOb1NvdmZUakFpZW56S3JFc2UwSHNXYkNaWm8KaC8zcmtDd3ZyTFBuT0VtRHdIN214b3JJVUZGOE9OOWRybUZNbEl0VzduMWtDREhMdzNJaWg1M1VDK0tmazJZTwpTTkQxTDErdWZ3b1NvRVRBWGpmRU94eERUZ1JPTjh1S1ZNZ3U2VloybCtmSnlmSlN6Qlh3Q1pqMmNCZlh3dGdwCnRQd2xCMWI1UUtLby9XQWh4TGZ4RjZ2djdCT0dkcHlEeEFCcjBaaE9DUEtVbDBlQUhpUmNDTElEejBWT1IxczgKZUIzY0ZFMjcxd1I5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: eks-dev
contexts:
- context:
    cluster: eks-dev
    user: aws
  name: eks-dev
current-context: eks-dev
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: "client.authentication.k8s.io/v1"
      command: "aws"
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "eks-dev"

